# Generated by Django 4.0.6 on 2022-07-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=127, verbose_name='Название общественного питания')),
                ('description', models.TextField(verbose_name='Описание общественного питания')),
                ('logo', models.ImageField(upload_to='./logo_caterings', verbose_name='Логотип общ питания')),
                ('address', models.CharField(max_length=225, verbose_name='Адрес общ питания')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
