# Generated by Django 4.0.6 on 2022-07-16 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caterings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catering',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelTable(
            name='catering',
            table='catering',
        ),
    ]
