# Generated by Django 4.0.6 on 2022-07-16 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caterings', '0002_alter_catering_options_alter_catering_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catering',
            options={'verbose_name': 'Catering', 'verbose_name_plural': 'Caterings'},
        ),
    ]
